spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: admin01

  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8081

